version: 2
jobs:
  build-test:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build
      - run: yarn test
      - persist_to_workspace:
          root: ~/repo
          paths:
            - build
            - ansible

  deploy-dev:
    docker:
      - image: circleci/python:2.7
        environment:
            ANSIBLE_HOST_KEY_CHECKING: no
            ANSIBLE_REMOTE_TEMP: /home/ubuntu/.ansible/tmp
    working_directory: ~/repo
    steps:
      - run: sudo pip install ansible
      - run: sudo apt install -y rsync
      - attach_workspace:
          at: ~/repo
      - run: ansible-playbook ./ansible/deploy.yml -i ./ansible/dev -t copy_www,fix_robots

  deploy-prod:
    docker:
      - image: circleci/python:2.7
        environment:
            ANSIBLE_HOST_KEY_CHECKING: no
            ANSIBLE_REMOTE_TEMP: /home/ubuntu/.ansible/tmp
    working_directory: ~/repo
    steps:
      - run: sudo pip install ansible
      - run: sudo apt install -y rsync
      - attach_workspace:
          at: ~/repo
      - run: ansible-playbook ./ansible/deploy.yml -i ./ansible/prod -t copy_www,fix_robots

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-test
      - deploy-dev:
          requires:
            - build-test
          filters:
            branches:
              only: dev
      - deploy-prod:
          requires:
            - build-test
          filters:
            branches:
              only: master