version: 2
jobs:
  build-test:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build
      - run: yarn test
      - persist_to_workspace:
          root: ~/repo
          paths:
            - build
            - ansible

  deploy-dev:
    docker:
      - image: circleci/python:2.7
    working_directory: ~/repo
    steps:
      - run: sudo pip install awscli --upgrade
      - run: aws --version
      - attach_workspace:
          at: ~/repo
      - run: aws s3 sync build/ s3://dev.getesf.com --delete

  deploy-beta:
    docker:
      - image: circleci/python:2.7
    working_directory: ~/repo
    steps:
      - run: sudo pip install awscli --upgrade
      - run: aws --version
      - attach_workspace:
          at: ~/repo
      - run: aws s3 sync build/ s3://getesf.com --delete

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-test
      - deploy-dev:
          requires:
            - build-test
          filters:
            branches:
              only: master
      - deploy-beta:
          requires:
            - build-test
          filters:
            branches:
              only: beta
