version: 2
jobs:
  unit-test:
    docker:
      - image: circleci/node:6.11.5
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test

  build-dev:
    docker:
      - image: circleci/node:6.11.5
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - build
            - ansible
      - run: echo "build-dev"

  build-prod:
    docker:
      - image: circleci/node:6.11.5
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - build
            - ansible
      - run: echo "build-prod"

  deploy-dev:
    docker:
      - image: circleci/python:3.6.4
    working_directory: ~/repo
    steps:
      - run: sudo pip install ansible
      - attach_workspace:
          at: ~/repo
      - run: mkdir ~/.ssh && ssh-keyscan -H 52.52.165.140 >> ~/.ssh/known_hosts
      - run: ANSIBLE_LOCAL_TEMP=$HOME/.ansible/tmp ANSIBLE_REMOTE_TEMP=/home/ubuntu/.ansible/tmp ansible-playbook ./ansible/deploy.yml -i ./ansible/dev -t copy_www,fix_robots

  deploy-prod:
    docker:
      - image: circleci/python:3.6.4
    working_directory: ~/repo
    steps:
      - run: sudo pip install ansible
      - attach_workspace:
          at: ~/repo
      - run: ls -la build
      - run: echo "deploy-prod"
      #- run: ansible-playbook site.yml

workflows:
  version: 2
  build-deploy:
    jobs:
      - unit-test
      - build-dev:
          requires:
            - unit-test
          filters:
            branches:
              only: test
      - build-prod:
          requires:
            - unit-test
          filters:
            branches:
              only: master
      - deploy-dev:
          requires:
            - build-dev
          filters:
            branches:
              only: test
      - deploy-prod:
          requires:
            - build-prod
          filters:
            branches:
              only: master