version: 2
jobs:
  build-test:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build
      - run: yarn test
      - persist_to_workspace:
          root: ~/repo
          paths:
            - build
            - ansible

  deploy-dev:
    docker:
      - image: ansible/ansible:ubuntu1604
        environment:
            ANSIBLE_HOST_KEY_CHECKING: no
    working_directory: ~/repo
    steps:
      - run: pip install ansible
      - attach_workspace:
          at: ~/repo
      - run: ANSIBLE_REMOTE_TEMP=/home/ubuntu/.ansible/tmp ansible-playbook ./ansible/deploy.yml -i ./ansible/dev -t copy_www,fix_robots

  deploy-prod:
    docker:
      - image: circleci/python:3.6.4
    working_directory: ~/repo
    steps:
      - run: sudo pip install ansible
      - attach_workspace:
          at: ~/repo
      - run: ls -la build
      - run: echo "deploy-prod"
      #- run: ansible-playbook site.yml

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-test
      - deploy-dev:
          requires:
            - build-test
          filters:
            branches:
              only: test
      - deploy-prod:
          requires:
            - build-test
          filters:
            branches:
              only: master